# CI CD for starter theme
name: CI/CD
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 12
          cache: 'npm'

      - name: Install Node Modules
        run: npm i

      - name: Build App
        run: npm run prod


      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy Theme files to server via SSH
        run: |
            sshpass -p "${{ secrets.KEY }}" scp -o StrictHostKeyChecking=no -r ./dist/theme/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/cicd/starter/wp-content/themes/starter/

      - name: Copy Plugins files to server via SSH
        run: |
            sshpass -p "${{ secrets.KEY }}" scp -o StrictHostKeyChecking=no -r ./dist/plugin/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/cicd/starter/wp-content/plugins/ale-core/

      - name: Copy docker-compose.yml to server
        run: |
            sshpass -p "${{ secrets.KEY }}" scp -o StrictHostKeyChecking=no ./docker-compose.yml ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/cicd/starter/

      - name: Deploy with docker-compose
        run: |
            sshpass -p "${{ secrets.KEY }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /root/cicd/starter && docker-compose down && docker-compose up -d"